spring:
  application:
    name: green_server
  profiles:
    active: local
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  datasource:
    platform: maria
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/green"
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
        type:
          descriptor:
            sql: trace
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: oceana5785@gmail.com
    password: gibcfckgbuyrtnyu
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls.enable: true

server:
  port: 8080
jwt:
  token:
    header: api_key
    issuer: green_server
    clientSecret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expirySeconds: 0

logging.level:
  root: info
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE